spring:
  datasource:
    url: jdbc:mysql://192.168.156.22:3306/devops?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Tv75aYT8@
  elasticsearch:
    uris: 192.168.156.22:9200
    connection-timeout: 3000
    socket-timeout: 30000
    connection-request-timeout: 30000
    password:
    username:

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.lamp.devops.controller